### PR TITLE
Ericson2314 self-nominate

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by fgaz** [comment]
!endorse

**Comment by lovesegfault** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by bryanhonof** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by numinit** [comment]
!endorse

Thank you for your work!

**Comment by ElvishJerricco** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by uninsane** [comment]
!endorse

**Comment by mkg20001** [comment]
!endorse

**Comment by vlinkz** [comment]
!endorse

**Comment by Pamplemousse** [comment]
!endorse

**Comment by asymmetric** [comment]
!endorse

**Comment by imincik** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by proofconstruction** [comment]
!endorse

**Comment by AndersonTorres** [comment]
!endorse

**Comment by Mic92** [comment]
!endorse

**Comment by Artturin** [comment]
!endorse

**Comment by SuperSandro2000** [comment]
!endorse

**Comment by Ekleog** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Pull request merged**
