### PR TITLE
Nominate nyabinary

### PR DESCRIPTION
**Pull request by expipiplus1**

### CODE REVIEW

**Comment by cafkafk** [comment]
!endorse

**Comment by nyabinary** [comment]
I accept this nomination :3

**Comment by NotAShelf** [comment]
!endorse

**Comment by FedericoSchonborn** [comment]
!endorse

**Comment by tomodachi94** [comment]
!endorse

**Comment by emilytrau** [comment]
!endorse

**Comment by mkg20001** [comment]
!endorse

**Comment by Scrumplex** [comment]
!endorse

**Comment by Gabriella439** [comment]
!endorse

**Comment by yukiisbored** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement and submitted the nomination form, which makes them a valid candidate.

**Pull request merged**
