### PR TITLE
Nominate numinit

### PR DESCRIPTION
**Pull request by agbrooks**

### CODE REVIEW

**Comment by tomodachi94** [comment]
!endorse

**Comment by numinit** [comment]
I accept.

**Comment by siriobalmelli** [comment]
!endorse

**Comment by cmm** [comment]
!endorse

**Comment by tomberek** [comment]
!endorse

**Comment by paperdigits** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. As soon as we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by RossComputerGuy** [comment]
!endorse

**Pull request merged**
