### PR TITLE
Nominate getchoo

### PR DESCRIPTION
**Pull request by nyabinary**

### CODE REVIEW

**Comment by getchoo** [comment]
I accept this nomination :)

**Comment by Scrumplex** [comment]
!endorse

**Comment by PedroHLC** [comment]
!endorse

**Comment by GeopJr** [comment]
!endorse

**Comment by vlinkz** [comment]
!endorse

**Comment by expipiplus1** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement and submitted the nomination form, which makes them a valid candidate.

**Pull request merged**
