### PR TITLE
Add winterqt as a candidate

### PR DESCRIPTION
**Pull request by winterqt**

### CODE REVIEW

**Comment by nyabinary** [comment]
!endorse

**Comment by emilytrau** [comment]
!endorse

**Comment by Aleksanaa** [comment]
!endorse

**Comment by Aleksanaa** [comment]
She is catgirl? fwiw i don't think i'm also

**Comment by Aleksanaa** [comment]
😨

**Comment by doronbehar** [comment]
!endorse

**Comment by deviant** [comment]
!endorse

**Comment by lilyball** [comment]
!endorse

**Comment by tomodachi94** [comment]
!endorse

**Comment by infinisil** [comment]
@tomodachi94 To complete your endorsement, please reply to the email asking for your conflicts of interest that has been sent to your [voter email address](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md). If it doesn't arrive within a couple minutes, check the spam folder or [get in touch with the EC](https://github.com/NixOS/SC-election-2024/tree/main?tab=readme-ov-file#election-committee-ec).

(briefly taking over because automation failed)

**Comment by wineee** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by Scrumplex** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Comment by mweinelt** [comment]
!endorse

**Comment by FedericoSchonborn** [comment]
!endorse

**Comment by infinisil** [comment]
Bad bot!

**Comment by cafkafk** [comment]
!endorse

**Comment by ocfox** [comment]
!endorse

**Comment by GovanifY** [comment]
!endorse

**Comment by thiagokokada** [comment]
!endorse

**Comment by wamserma** [comment]
!endorse

**Comment by Ekleog** [comment]
!endorse

**Comment by adamcstephens** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by SebTM** [comment]
!endorse

**Comment by vinnymeller** [comment]
!endorse

**Pull request merged**
