### PR TITLE
Nominate edolstra

### PR DESCRIPTION
**Pull request by nrdxp**

### CODE REVIEW

**Comment by azahi** [comment]
!endorse

**Comment by cmm** [comment]
!endorse

**Comment by numinit** [comment]
!endorse

**Comment by bryanhonof** [comment]
!endorse

**Comment by vojta001** [comment]
!endorse

**Comment by ners** [comment]
!endorse

**Comment by misuzu** [comment]
!endorse

**Comment by agbrooks** [comment]
!endorse

**Comment by 06kellyjac** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. In case they accept the nomination and we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by nyabinary** [comment]
@nrdxp Did you ask Eelco beforehand if he wanted to run before nominating him [according to this](https://github.com/NixOS/SC-election-2024/blob/main/doc/nominate.md#how-to-nominate-somebody-else) it's best to ask a person *before* nominating them if they want to be nominated: “and ask them if they'd like to be nominated.”

**Comment by b-rodrigues** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by pbek** [comment]
!endorse

**Comment by hellwolf** [comment]
!endorse

**Comment by stepbrobd** [comment]
!endorse

**Comment by mkg20001** [comment]
!endorse

**Comment by vinnymeller** [comment]
!endorse

**Comment by infinisil** [comment]
The nominee has not accepted

**Pull request closed without merging**
