### PR TITLE
Nominate tomberek

### PR DESCRIPTION
**Pull request by tomodachi94**
While working with @tomberek on the NixOS Discord moderation team, I've noticed that Tom always puts the well-being of the community first, which is the main thing that I believe candidates should have. Tom always assumes good faith and always attempts to educate others, making him an excellent candidate.

### CODE REVIEW

**Comment by numinit** [comment]
Tom tirelessly works on Nix related projects and the community, +1 :-)

!endorse

**Comment by djacu** [comment]
!endorse

**Comment by asymmetric** [comment]
!endorse

**Comment by RossComputerGuy** [comment]
!endorce

**Comment by RossComputerGuy** [comment]
!endorse

**Comment by fufexan** [comment]
!endorse

**Comment by bryanhonof** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Comment by imincik** [comment]
!endorse

**Comment by Aleksanaa** [comment]
> EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

Tom has not confirmed to accept the nomination yet.

**Comment by infinisil** [comment]
Good point, will need confirmation of course :)

**Comment by Ekleog** [comment]
!endorse

**Comment by tomberek** [comment]
> @tomberek: You've been nominated! To accept, please indicate so with a comment.

I accept.

**Comment by infinisil** [comment]
Thank you, this confirms you as a candidate!

**Comment by imincik** [comment]
!endorse

**Pull request merged**
