### PR TITLE
Nominate fpletz

### PR DESCRIPTION
**Pull request by fpletz**

### CODE REVIEW

**Comment by Mic92** [comment]
!endorse

**Comment by Ma27** [comment]
!endorse

**Comment by Ericson2314** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by arianvp** [comment]
!endorse

**Comment by adisbladis** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by spacefrogg** [comment]
!endorse

**Comment by grahamc** [comment]
!endorse

**Comment by Aleksanaa** [comment]
!endorse

**Comment by matthiasbeyer** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. As soon as we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by jian-lin** [comment]
!endorse

**Comment by SebTM** [comment]
!endorse

**Comment by kloenk** [comment]
!endorse

**Pull request merged**
