### PR TITLE
Nominate linsui

### PR DESCRIPTION
**Pull request by Aleksanaa**
@linsui has done [considerably large amount of contributions](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Alinsui+is%3Aclosed) in the last several year, and is always enthusiastic to help and guide newcomers in the NixOS Chinese group.

### CODE REVIEW

**Comment by linsui** [comment]
I accept. :)

**Comment by tomodachi94** [comment]
!endorse

**Comment by linyinfeng** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by AndersonTorres** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Pull request merged**
