### PR TITLE
Nominate asymmetric

### PR DESCRIPTION
**Pull request by asymmetric**

### CODE REVIEW

**Comment by phaer** [comment]
!endorse

**Comment by proofconstruction** [comment]
!endorse

**Comment by djacu** [comment]
!endorse

**Comment by zimbatm** [comment]
!endorse

**Comment by numinit** [comment]
!endorse

**Comment by arianvp** [comment]
!endorse

**Comment by d-xo** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. As soon as we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Pull request merged**
