### PR TITLE
Nominate cafkafk

### PR DESCRIPTION
**Pull request by nyabinary**
@cafkafk has [done a ton of solid work in nixpkgs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Acafkafk+) and in the nix community in general, which is why I'm nominating her today :3

### CODE REVIEW

**Comment by cafkafk** [comment]
> To accept, please indicate so with a comment.

I accept!

**Comment by Scrumplex** [comment]
!endorse

**Comment by Aleksanaa** [comment]
!endorse

**Comment by FedericoSchonborn** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by vlinkz** [comment]
!endorse

**Comment by nyabinary** [comment]
Whoops :P

**Comment by emilytrau** [comment]
!endorse

**Comment by LudovicoPiero** [comment]
!endorse

**Comment by pbek** [comment]
!endorse

**Comment by wamserma** [comment]
!endorse

**Comment by GeopJr** [comment]
!endorse

**Comment by fgaz** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Pull request merged**
