### PR TITLE
Nominate scrumplex

### PR DESCRIPTION
**Pull request by Aleksanaa**
Sefa Eyeoglu (@Scrumplex) has made numerous contributions to Nixpkgs over the past few years. Despite his humble nature and reserved communication style, he is deeply passionate about enhancing the Nixpkgs community. Many of his ideas align closely with the improvements we are striving to achieve today. At the same time, as someone who works as a DevOps engineer, I believe he has a sharper instinct for the right direction in our technological development.

I'll cite his self-statement during the NCA nomination as a temporary source: https://nixpkgs.zulipchat.com/#narrow/stream/436732-Constitutional-assembly-applications/topic/Sefa.20.2F.20Scrumplex

### CODE REVIEW

**Comment by tomodachi94** [comment]
!endorse

**Comment by Scrumplex** [comment]
> You've been nominated! To accept, please indicate so with a comment.

I accept this nomination ^^

**Comment by nyabinary** [comment]
!endorse

**Comment by FedericoSchonborn** [comment]
!endorse

**Comment by infinisil** [comment]
@vlinkz You've already been asked to disclose your conflicts of interest after a previous endorsement. So the endorsement is already complete if you replied to that email (sent to your [voter email address](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md)). If you never received that, check the spam folder or [get in touch with the EC](https://github.com/NixOS/SC-election-2024/tree/main?tab=readme-ov-file#election-committee-ec).

**Comment by getchoo** [comment]
!endorse

**Comment by pyrox0** [comment]
!endorse

**Comment by cafkafk** [comment]
!endorse

**Comment by infinisil** [comment]
@cafkafk You've already been asked to disclose your conflicts of interest after a previous endorsement. So the endorsement is already complete if you replied to that email (sent to your [voter email address](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md)). If you never received that, check the spam folder or [get in touch with the EC](https://github.com/NixOS/SC-election-2024/tree/main?tab=readme-ov-file#election-committee-ec).

**Comment by PedroHLC** [comment]
!endorse

**Comment by loicreynier** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Comment by infinisil** [comment]
Correction: Scrumplex has already submitted the form, so I will merge this right now :)

**Pull request merged**
