### PR TITLE
Nominate nlewo

### PR DESCRIPTION
**Pull request by zimbatm**
Antoine Eiche is focused on building things and bringing good energy to the project.

https://github.com/nlewo

### CODE REVIEW

**Comment by numinit** [comment]
!endorse

**Comment by Mic92** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. In case they accept the nomination and we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by nlewo** [comment]
Thank you for these endorsements.
However, i won't be able to find enough time to correctly assume this role. 
So, i prefer to decline my nomination.

**Comment by infinisil** [comment]
Alright, let's close this then :)

**Pull request closed without merging**
