### PR TITLE
Nominate adisbladis

### PR DESCRIPTION
**Pull request by infinisil**

### CODE REVIEW

**Comment by adisbladis** [comment]
> @adisbladis: You've been nominated! To accept, please indicate so with a comment.

I accept

**Comment by tomodachi94** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by l0b0** [comment]
!endorse

**Comment by hsjobeki** [comment]
!endorse

**Comment by phaer** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by zupo** [comment]
!endorse

**Comment by cmm** [comment]
!endorse

**Comment by thiagokokada** [comment]
!endorse

**Comment by stigtsp** [comment]
!endorse

**Comment by bryanhonof** [comment]
!endorse

**Comment by Kranzes** [comment]
!endorse

**Comment by MatthewCroughan** [comment]
!endorse

**Comment by AndersonTorres** [comment]
!endorse

**Comment by Mic92** [comment]
!endorse

**Comment by Ekleog** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Comment by ryantm** [comment]
!endorse

**Pull request merged**
