### PR TITLE
Nominate yu-re-ka

### PR DESCRIPTION
**Pull request by alyssais**

### CODE REVIEW

**Comment by nyabinary** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by expipiplus1** [comment]
!endorse

**Comment by leona-ya** [comment]
!endorse

**Comment by arianvp** [comment]
!endorse

**Comment by liclac** [comment]
!endorse

**Comment by emilytrau** [comment]
!endorse

**Comment by mkg20001** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by philiptaron** [comment]
!endorse

**Comment by afh** [comment]
!endores

**Comment by afh** [comment]
!endorse

**Comment by phaer** [comment]
!endorse

**Comment by Stunkymonkey** [comment]
!endorse

**Comment by lukegb** [comment]
!endorse

**Comment by devusb** [comment]
!endorse

**Comment by yayayayaka** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement and submitted the nomination form, which makes them a valid candidate.

**Pull request merged**
