### PR TITLE
Nominate NotAShelf

### PR DESCRIPTION
**Pull request by nyabinary**

### CODE REVIEW

**Comment by NotAShelf** [comment]
I accept.

**Comment by PedroHLC** [comment]
!endorse

**Comment by itslychee** [comment]
!endorse

**Comment by tomodachi94** [comment]
!endorse

**Comment by amadejkastelic** [comment]
!endorse

**Comment by adamcstephens** [comment]
!endorse

**Comment by RossComputerGuy** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. As soon as we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by Sigmanificient** [comment]
!endorse

**Pull request merged**
