### PR TITLE
Nominate Gabriella439

### PR DESCRIPTION
**Pull request by nyabinary**

### CODE REVIEW

**Comment by Gabriella439** [comment]
I accept this nomination

**Comment by proofconstruction** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by lilyball** [comment]
!endorse

**Comment by LunNova** [comment]
!endorse

**Comment by FedericoSchonborn** [comment]
!endorse

**Comment by cafkafk** [comment]
!endorse

**Comment by ryantm** [comment]
!endorse

**Comment by vlinkz** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by balsoft** [comment]
!endorse

**Comment by pingiun** [comment]
!endorse

**Comment by ju1m** [comment]
!endorse

**Comment by d-xo** [comment]
!endorse

**Comment by CertainLach** [comment]
!endorse

**Comment by yukiisbored** [comment]
!endorse

**Comment by akirak** [comment]
!endorse

**Comment by expipiplus1** [comment]
!endorse

**Comment by virusdave** [comment]
!endorse

**Comment by emilytrau** [comment]
!endorse

**Comment by fpletz** [comment]
!endorse

**Comment by Ericson2314** [comment]
!endorse

**Comment by mrcjkb** [comment]
!endorse

**Comment by Scrumplex** [comment]
!endorse

**Comment by siriobalmelli** [comment]
!endorse

**Comment by fabianhjr** [comment]
Regarding Aproval Voting

Thoughts on Reweighted Approval Voting / Sequential Proportional Approval Voting for multiple winners elections?

**Pull request merged**
