### PR TITLE
Nominate jtojnar

### PR DESCRIPTION
**Pull request by mkg20001**

### CODE REVIEW

**Comment by Ericson2314** [comment]
!endorse

**Comment by winterqt** [comment]
!endorse

**Comment by Aleksanaa** [comment]
!endorse

**Comment by misuzu** [comment]
!endorse

**Comment by cmm** [comment]
!endorse

**Comment by azahi** [comment]
!endorse

**Comment by mweinelt** [comment]
!endorse

**Comment by getchoo** [comment]
!endorse

**Comment by vojta001** [comment]
!endorse

**Comment by philiptaron** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by spacefrogg** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. In case they accept the nomination and we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by ryantm** [comment]
!endorse

**Comment by jian-lin** [comment]
!endorse

**Comment by jtojnar** [comment]
Thank you for the nomination and endorsements. I accept.

**Pull request merged**
