### PR TITLE
Nominate infinidoge

### PR DESCRIPTION
**Pull request by nyabinary**

### CODE REVIEW

**Comment by Infinidoge** [comment]
I accept this nomination :)

**Comment by Scrumplex** [comment]
!endorse

**Comment by infinisil** [comment]
@Scrumplex You've already been asked to disclose your conflicts of interest after a previous endorsement. So the endorsement is already complete if you replied to that email (sent to your [voter email address](https://github.com/NixOS/SC-election-2024/blob/main/doc/email.md)). If you never received that, check the spam folder or [get in touch with the EC](https://github.com/NixOS/SC-election-2024/tree/main?tab=readme-ov-file#election-committee-ec).

**Comment by doronbehar** [comment]
!endorse

**Comment by GeopJr** [comment]
!endorse

**Comment by philiptaron** [comment]
!endorse

**Pull request merged**
