### PR TITLE
Nominate roberth

### PR DESCRIPTION
**Pull request by bergkvist**

### CODE REVIEW

**Comment by jian-lin** [comment]
!endorse

**Comment by agbrooks** [comment]
!endorse

**Comment by getchoo** [comment]
!endorse

**Comment by SebTM** [comment]
!endorse

**Comment by cmm** [comment]
!endorse

**Comment by edwtjo** [comment]
!endorse

**Comment by ysndr** [comment]
!endorse

**Comment by bryanhonof** [comment]
!endorse

**Comment by tfc** [comment]
!endorse

**Comment by gbtb** [comment]
!endorse

**Comment by siriobalmelli** [comment]
!endorse

**Comment by Stunkymonkey** [comment]
!endorse

**Comment by tomberek** [comment]
!endorse

**Comment by uninsane** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This nominee has met the endorsements requirement. In case they accept the nomination and we receive their filled-out candidate form, this PR will be merged, making them a valid candidate.

**Comment by roberth** [comment]
I accept

**Pull request merged**
