### PR TITLE
lovesegfault self-nominate

### PR DESCRIPTION
**Pull request by lovesegfault**

### CODE REVIEW

**Comment by winterqt** [comment]
!endorse

**Comment by NickCao** [comment]
!endorse

**Comment by Ericson2314** [comment]
!endorse

**Comment by xgroleau** [comment]
!endorse

**Comment by Aleksanaa** [comment]
!endorse

**Comment by Pamplemousse** [comment]
!endorse

**Comment by picnoir** [comment]
!endorse

**Comment by Mic92** [comment]
!endorse

**Comment by Ekleog** [comment]
!endorse

**Comment by fgaz** [comment]
!endorse

**Comment by phaer** [comment]
!endorse

**Comment by mkg20001** [comment]
!endorse

**Comment by kloenk** [comment]
!endorse

**Comment by tomberek** [comment]
!endorse

**Comment by talyz** [comment]
!endorse

**Comment by misuzu** [comment]
!endorse

**Comment by infinisil** [comment]
EC: This candidate has met the endorsements requirement. As soon as we receive the candidate's filled-out form, this PR will be merged.

**Comment by jian-lin** [comment]
!endorse

**Pull request merged**
